language: go

go:
  - 1.7.1

before_install:
  - ./write_netrc.sh
  - cp .netrc ~
  - chmod 600 .netrc
  - pip3 install requests

script:
  - make publish

services:
  - docker

notifications:
  email: false

branches:
  only:
  - master
