language: go

go:
  - 1.7.1

before_install:
  - ./write_netrc.sh
  - cp .netrc ~
  - chmod 600 .netrc
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3

script:
  - make publish

services:
  - docker
