Name = "squarescale-cli/sqsc"
Owner = "squarescale"
Version = "0.1.0"
Description = "Squarescale CLI"
Framework = "go_cmd"

[[Commands]]
  Name = "login"
  FunctionName = "login"
  Synopsis = ""
  Help = ""
