name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Configure GIT for Go private modules
      env:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: git config --global url."https://squarescale-bot:${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Setup GO env
      run: go env -w GOPRIVATE=github.com/squarescale

    - name: Get dependencies
      run:  go get -v -t -d ./...

    - name: Test
      run: go test ./...

    - name: Build
      run: go build -v .
